// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {cursor} from '../models';
import {update} from '../models';
import {main} from '../models';
import {store} from '../models';
import {mux} from '../models';

export function ApplyToCursor():Promise<cursor.Status>;

export function ApplyUpdate():Promise<void>;

export function CheckUpdate():Promise<update.Status>;

export function ConfirmClose(arg1:main.CloseDecision):Promise<void>;

export function DeleteProvider(arg1:string):Promise<void>;

export function GetDashboard():Promise<main.Dashboard>;

export function OpenCursorDownload():Promise<void>;

export function OpenReleasePage():Promise<void>;

export function QuitApp():Promise<void>;

export function RefreshModels(arg1:string):Promise<Array<string>>;

export function RestoreCursor():Promise<cursor.RestoreResult>;

export function SaveProvider(arg1:main.SaveRequest):Promise<main.ProviderView>;

export function SetProviderEnabled(arg1:string,arg2:boolean):Promise<void>;

export function SetTheme(arg1:string):Promise<store.Prefs>;

export function ShowWindow():Promise<void>;

export function StartGateway():Promise<mux.Status>;

export function StopGateway():Promise<void>;
