// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyToCursor() {
  return window['go']['main']['App']['ApplyToCursor']();
}

export function ApplyUpdate() {
  return window['go']['main']['App']['ApplyUpdate']();
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function ConfirmClose(arg1) {
  return window['go']['main']['App']['ConfirmClose'](arg1);
}

export function DeleteProvider(arg1) {
  return window['go']['main']['App']['DeleteProvider'](arg1);
}

export function GetDashboard() {
  return window['go']['main']['App']['GetDashboard']();
}

export function OpenCursorDownload() {
  return window['go']['main']['App']['OpenCursorDownload']();
}

export function OpenReleasePage() {
  return window['go']['main']['App']['OpenReleasePage']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function RefreshModels(arg1) {
  return window['go']['main']['App']['RefreshModels'](arg1);
}

export function RestoreCursor() {
  return window['go']['main']['App']['RestoreCursor']();
}

export function SaveProvider(arg1) {
  return window['go']['main']['App']['SaveProvider'](arg1);
}

export function SetProviderEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetProviderEnabled'](arg1, arg2);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartGateway() {
  return window['go']['main']['App']['StartGateway']();
}

export function StopGateway() {
  return window['go']['main']['App']['StopGateway']();
}
